@NatechAssignmentWebService_HostAddress = https://localhost:7169

GET {{NatechAssignmentWebService_HostAddress}}/ipgeolocation?ipAddress=string

###

POST {{NatechAssignmentWebService_HostAddress}}/ipgeolocation
Content-Type: application/json

[
  "1.1.1.1",
  "8.8.8.8"
]

###

GET {{NatechAssignmentWebService_HostAddress}}/ipgeolocation/GetLocationForListOfIpStatus/string

###
